services:
  - type: web
    name: ies-data-viz
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
